// swift-tools-version: 5.10
import PackageDescription

let package = Package(
    name: "Kits",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "DesignSystem",  targets: ["DesignSystem"]),
        .library(name: "AppFoundation", targets: ["AppFoundation"]),
        .library(name: "PaywallKit",    targets: ["PaywallKit"]),
        .library(name: "SettingsKit",   targets: ["SettingsKit"]),
        .library(name: "PersistenceKit",targets: ["PersistenceKit"]),
        .library(name: "SyncKit",       targets: ["SyncKit"]),
        .library(name: "SecurityKit",   targets: ["SecurityKit"]),
        .library(name: "NetworkKit",    targets: ["NetworkKit"]),
        .library(name: "CameraKit",     targets: ["CameraKit"]),
        .library(name: "RenderKit",     targets: ["RenderKit"]),
        .library(name: "ChartsKit",     targets: ["ChartsKit"]),
        .library(name: "VisionScanKit", targets: ["VisionScanKit"]),
        .library(name: "PaymentsKit",   targets: ["PaymentsKit"]),
    ],
    targets: [
        .target(name: "DesignSystem"),
        .target(name: "AppFoundation"),
        .target(name: "PaywallKit",     dependencies: ["AppFoundation", "DesignSystem"],
                resources: [.copy("Resources/Configuration.storekit")]),
        .target(name: "SettingsKit",    dependencies: ["DesignSystem", "AppFoundation", "PaywallKit"]),
        .target(name: "PersistenceKit"),
        .target(name: "SyncKit",        dependencies: ["PersistenceKit"]),
        .target(name: "SecurityKit"),
        .target(name: "NetworkKit"),
        .target(name: "CameraKit",      dependencies: ["RenderKit"]),
        .target(name: "RenderKit",
                resources: [.copy("Shaders/Shaders.metal")]),
        .target(name: "ChartsKit",      dependencies: ["RenderKit"],
                resources: [.copy("Shaders/ChartShaders.metal")]),
        .target(name: "VisionScanKit",  dependencies: ["CameraKit"]),
        .target(name: "PaymentsKit"),
        .testTarget(name: "DesignSystemTests",    dependencies: ["DesignSystem"]),
        .testTarget(name: "PaywallKitTests",      dependencies: ["PaywallKit"]),
        .testTarget(name: "SettingsKitTests",     dependencies: ["SettingsKit"]),
        .testTarget(name: "PersistenceKitTests",  dependencies: ["PersistenceKit"]),
        .testTarget(name: "AppFoundationTests",   dependencies: ["AppFoundation"]),
        .testTarget(name: "SecurityKitTests",     dependencies: ["SecurityKit"]),
        .testTarget(name: "NetworkKitTests",      dependencies: ["NetworkKit"],
                    resources: [.process("Fixtures")]),
        .testTarget(name: "RenderKitTests",       dependencies: ["RenderKit"]),
        .testTarget(name: "ChartsKitTests",       dependencies: ["ChartsKit"]),
        .testTarget(name: "CameraKitTests",       dependencies: ["CameraKit"]),
        .testTarget(name: "VisionScanKitTests",   dependencies: ["VisionScanKit"]),
        .testTarget(name: "PaymentsKitTests",     dependencies: ["PaymentsKit"]),
        .testTarget(name: "SyncKitTests",         dependencies: ["SyncKit"]),
    ]
)
